### ISSUE TITLE
Initial roadmap for high-level cyberinfrastructure components of analysis system

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#11]
## Assumptions

High-level cyberinfrastructure components include:
 - INSPIRE
 - HEPData
 - CERN Analysis Preservation framework
 - CERN Open Data
 - REANA
 - INDICO
 - Zenodo
 - RECAST
 - GitHub and GitLab at CERN

These projects are pre-existing and funded through a variety of mechanisms (sometimes including IRIS-HEP). IRIS-HEP's role is largely about 
 - integration with analysis system tools (eg. pyhf and HEPData)
 - enhancing interoperability between those components (eg. RECAST, CAP, REANA, HEPData)

## Acceptance criteria

 - figure or other documentation describing interaction of components needed to achieve specific analysis user stories (eg. on-boarding, reinterpretation, publishing, preservation). 
 - pointeres to specific engagements with these cyberinfrastructure components (eg. via GitHub issues)

**Comment by matthewfeickert** [comment]
@cranmer @gordonwatts Can you give some feedback on what the goals of this Milestone are? It wasn't really clear to anyone in the AS meeting on 2020-02-05, so as they are due soon it would be good to understand how to move forward.

**Edit:** Comments from @gordonwatts and @msneubauer later in the meeting.

What infrastructure are you going to host all the different parts of the AS software pipeline on?

c.f. River at Chicago

@mweinberg2718 can you add some comments here as well about what you've done with Coffea and River?

**Comment by gordonwatts** [comment]
I would guess we need text that is about 1/2 a page for this - since it is mostly Hardware. There were some conclusions from the NYU blueprint meeting (@msneubauer), that might be relevant. It might be useful to use the ecosystem coherency to help here too.

**Comment by cranmer** [comment]
Had nice discussion with @lukasheinrich and @Sinclert about this. This should focus mainly on HEPData, INSPIRE, CAP, RECAST, etc. pyhf and fitting service are also related.

**Comment by cranmer** [comment]
See issue with HEPData: https://github.com/HEPData/hepdata/issues/164

**Comment by cranmer** [comment]
See issue: https://github.com/HEPData/hepdata/issues/163

**Comment by cranmer** [comment]
see issue: https://github.com/indico/indico/issues/4293

**Comment by cranmer** [comment]
See HEPData Advisory Board agenda: https://conference.ippp.dur.ac.uk/event/875/

**Comment by cranmer** [comment]
For reference, many ideas of this road map first discussed at AAHEP7 in 2014
https://indico.cern.ch/event/262430/sessions/48420/#20140402

**Comment by cranmer** [comment]
CERN press on publishing pyhf on HEPData:
https://home.cern/news/news/knowledge-sharing/new-open-release-allows-theorists-explore-lhc-data-new-way

**Comment by cranmer** [comment]
Initial roadmap tied to reinterpretation user story:
https://github.com/iris-hep/as-user-facing/blob/master/reinterpretation.md
