### ISSUE TITLE
GPU/accelerator-based implementation of statistical and other appropriate components

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#15]
# Assumptions 

- [x] There will be a working implementation of statistical software that can take advantage of hardware acceleration.

# Acceptance Criteria

- [x] pyhf can run on GPUs/TPUs
   - For some (admittedly old plots), one can see [CHEP 2019 poster](https://indico.cern.ch/event/773049/contributions/3476180/).

**Comment by matthewfeickert** [comment]
@gordonwatts @cranmer @msneubauer This is ready for review.
