### ISSUE TITLE
List publicly-accessible repositories and other relevant documentation on the iris-hep.org website

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#2]
# Assumptions 

This will be a living document, and informed by HOW workshop and HSF discussions

# Acceptance Criteria

- [x] An agreed upon format for listing the repositories.

**Comment by cranmer** [comment]
Completed with https://github.com/iris-hep/awesome-hep

**Comment by jpivarski** [comment]
Oops.
