### ISSUE TITLE
Survey of analysis systems efforts in the field to aid in planning for a topical workshop

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#4]
# Assumptions

 * As a community we are informally aware of the vast majority of the efforts in the field, though not all of them. 

 * Restricted to analysis software meant to be used by others, not code specific to an analysis
 
 * There are similar efforts in HSF and other places. This is not meant to be authoritative, but useful input stop to a planning workshop.

# Acceptance Criteria

 * A publicly accessible list of projects organized by type of analysis software. (Ideally crowd sourced)

**Comment by alexander-held** [comment]
Several IRIS-HEP members participated in a birds of a feather meeting dedicated to **Statistical Modeling in HEP** on Nov 7 at the CHEP2019 conference in Adelaide, Australia. The meeting included developers of [pyhf](https://github.com/scikit-hep/pyhf), [zfit](https://github.com/zfit/zfit), [RooFit](https://root.cern.ch/roofit), higher level frameworks and users. Meeting notes can be found [here](https://docs.google.com/document/d/1RruMCHA-Imes6NlmcYSP1-LVBMCdPhCeoK0MNdv28kE/preview).

The participants agreed on the importance of breaking down the various components of the statistical analysis workflow in HEP into independent modules, with well-defined interfaces between the modules. These interfaces should be adopted by all tools, to allow for interoperability. A community white paper is envisioned to describe the modules and interfaces (à la Les Houches Accords, example here for MC event generators [arXiv:hep-ph/0109068](https://arxiv.org/abs/hep-ph/0109068)).

The possibility of a topical workshop dedicated to converging on the specification was discussed and found to be a good idea. Such a workshop could take place around Spring-Summer 2020.

**Comment by cranmer** [comment]
Satisfied with this Awesome list:
https://github.com/iris-hep/awesome-hep

We should continue to update.
