### ISSUE TITLE
Blueprint workshop coordinating resource needs for evaluating analysis systems coordinated by SSL with the participation of operations program

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#5]
# Assumptions

# Acceptance Criteria

1. An agenda

1. appropriate members of SSL,  AS,  stakeholders attend.

1. Summary document

**Comment by cranmer** [comment]
Agenda: https://indico.cern.ch/event/820946/

Live notes attached to agenda

@msneubauer please add link to the final blueprint report.

**Comment by msneubauer** [comment]
The summary document for this workshop can be found at:

https://github.com/iris-hep/blueprint/blob/master/reports/2019/Analysis-Systems-on-Scalable-Platforms/report.pdf

Currently at version 0.9 but will be updated accordingly.
