### ISSUE TITLE
Prototype awkward-array analyses in the scientific Python ecosystem

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#6]
## Assumptions

Pythonic ecosystem refers to tools being developed by IRIS-HEP and scikit-hep such as uproot, awkward, etc.

## Acceptance Criteria

Demonstrated with an one of the analysis use cases chosen by the AS group.

Link to code is available 

Some for of a demo is presented.

**Comment by jpivarski** [comment]
Thanks to @nsmith-:

   * realistic Z peak [using TTree::GetEntry](https://github.com/nsmith-/coffea/blob/master/notebooks/ZPeak.C)
   * same Z peak [using awkward-arrays](https://nbviewer.jupyter.org/github/nsmith-/coffea/blob/master/notebooks/zpeak.ipynb)
   * analysis: https://indico.cern.ch/event/759388/contributions/3356303/
