### ISSUE TITLE
Organize topical meetings, Analysis System group meetings, etc

### ISSUE THREAD

**Issue by BenGalewsky** [iris-hep/project-milestones#7]
# Assumptions

# Acceptance Criteria
1. Schedule of regular times for topical meetings
2. There is a process for biweekly conference calls with templates and indico events

**Comment by BenGalewsky** [comment]
Meetings are now scheduled for every other Wednesday at 1:00 ET
We have templates for minutes and agenda

**Comment by cranmer** [comment]
Agendas are here: https://indico.cern.ch/category/10889/

Live note templates in Google Docs
